
GET http://localhost:5110/games

###
GET http://localhost:5110/games/3

###
POST http://localhost:5110/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "genreId": 4,
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###
PUT http://localhost:5110/games/4
Content-Type: application/json

{
  "name": "Final Fanatasy XIV",
  "genreId": 2,
  "price": 49.50,
  "releaseDate": "2010-09-30"
}

###
DELETE http://localhost:5110/games/2